const PROMPTS = [
  "Listen.",
  "Find time.",
  "Make time.",
  "Make space.",
  "Take up space.",
  "Mentor someone.",
  "Someone mentored you.",
  "Ask the stupid question.",
  "Interns are people, too.",
  "You were junior once, too.",
  "Identify key stakeholders.",
  "Climbing isn't everything.",
  "Is a great version possible?",
  "Sign off. Try again tomorrow.",
  "You can't solve this one alone.",
  "Pick the right tool for the job.",
  "The goal isn't to do everything.",
  "Leave room for others to get in.",
  "Bcc is an opportunity for whimsy.",
  "Your work is more than your output.",
  "You're allowed to ask for help, too.",
  "Thank the EA who booked the meeting.",
  "Check in with them instead of guessing.",
  "Who's falling off-grid? Pull them back.",
  "Ask the CEO what they're worried about.",
  "Ask questions. Before you try to solve.",
  "Memorize the receptionist's coffee order.",
  "Pick someone's brain. Let them pick yours.",
  "Eat at a lunch counter without your phone.",
  "Give people your full, undivided attention.",
  "Ask your boss what they're optimistic about.",
  "Someone new just started. Introduce yourself.",
  "Someone did something great today. Tell them!",
  "Ask colleagues about their favorite projects.",
  "Book a meeting that could have been an email.",
  "Zoom is faster. In-person is more meaningful.",
  "Have lunch. Even if you're in different cities.",
  "Who helped you fix it your last big mess at work?",
  "If you can do it alone, you're thinking too small.",
  "Find out people's birthdays. Do something cringey.",
  "Who helped you celebrate your last big win at work?",
  "Meet for coffee. Even if you're in different cities.",
  "Find an industry you're curious to learn more about.",
  "Ask the interns how they chose their favorite class.",
  "Remember why you wanted this job in the first place.",
  "What do you wish knew more about? Who is great at that?",
  "Who can help this job become the job you want it to be?",
  "Ask an exec which part of the strategy excites them most.",
  "Have a walking meeting. Even if you're in different cities.",
  "Grunt work goes fast when divided across a team with snacks.",
  "When was the last time someone took an interest in your career?",
  "Hydration matters. Give people time to get water before the meeting.",
  "Set up a video portal for mutli-city offices. Put it in the kitchen.",
  "Who helped you get your current gig? Have you spoken with them lately?",
  "Someone did something great last week. Tell them why it mattered to you.",
  "Organize happy hour. Remember, not everyone has the same defintion of happy.",
  "Your colleague just got back from travel. Ask them about the best thing they ate.",
  "Show your colleagues how something works. You may need to screenshare. That's ok.",
  "Ask a question. Pause and drink water while you wait for the next person to speak.",
  "Your best network ten years from now will be your peers today. How are they doing?",
  "Do not feign surprise when people don't know things. You don't know lots of things.",
  "Say thank you. Can't figure out what for? Close your eyes and count to ten. It'll come.",
  "Make a shared spreadsheet of every restaurant near your office. Include a notes column.",
  "Who — other than a bot — can teach you about the thing you're struggling with right now?",
  "Find the most junior person on the team. Teach them something it took you months to learn.",
  "You're not sure how someone feels about your work. Check in with them instead of guessing.",
  "Have your colleague teach you how something works. They may need to screenshare. That's ok.",
  "Global teams make great pen pals. Send predictions from the future. Or missives from the past.",
  "Can your next virtual meeting be over coffee? What if you were willing to restructure or reschedule it?",
]
