const PROMPTS = [
    "Someone new just started. Introduce yourself.",
  "Someone did something great today. Tell them!",
  "Hydration matters. Give people time to get water before the meeting.",
  "Have lunch. Even if you're in different cities.",
  "Ask a question. Pause and drink water while you wait for the next person to speak.",
  "Your colleague just got back from travel. Ask them about the best thing they ate.",
  "Global teams make great pen pals. Send predictions from the future. Or missives from the past.",
  "Say thank you. Can't figure out what for? Close your eyes and count to ten. It'll come.",
  "Show your colleagues how something works. You may need to screenshare. That's ok.",
  "Have your colleague teach you how something works. They may need to screenshare. That's ok.",
  "Have a walking meeting. Even if you're in different cities.",
  "Meet for coffee. Even if you're in different cities.",
  "Set up a video portal for mutli-city offices. Put it in the kitchen.",
  "Ask colleagues about their favorite projects.",
  "What do you wish knew more about? Who is great at that?",
  "Moving someone to bcc is an opportunity for whimsy.",
  "Find the most junior person on the team. Teach them something it took you months to learn.",
  "Mentor someone.",
  "You were junior once, too.",
  "If you can do it alone, you're thinking too small.",
  "Pick someone's brain. Let them pick yours.",
  "Book a meeting that could have been an email.",
  "Sign off. Try again tomorrow.",
  "Organize happy hour. Remember, not everyone has the same defintion of happy.",
  "Someone did something great last week. Tell them why it mattered to you.",
  "You're not sure how someone feels about your work. Check in with them instead of guessing.",
  "Check in with them instead of guessing.",
  "Who — other than a bot — can teach you about the thing you're struggling with right now?",
  "Ask an exec which part of the strategy excites them most.",
  "Who helped you get your current gig? Have you spoken with them lately?",
  "When was the last time someone took an interest in your career?",
  "Find an industry you're curious to learn more about.",
  "Eat at a lunch counter without your phone.",
  "Can your next virtual meeting be over coffee? What if you were willing to restructure or reschedule it?",
  "Zoom is faster. In-person is more meaningful.",
  "Who's falling off-grid? Pull them back.",
  "You're allowed to ask for help, too.",
  "Grunt work goes fast when divided across a team with snacks.",
  "You can't solve this one alone.",
  "Ask your boss what they're optimistic about.",
  "Ask the CEO what they're worried about.",
  "Ask the interns how they chose their favorite class.",
  "Memorize the receptionist's coffee order.",
  "Thank the EA who booked the meeting.",
  "Leave room for others to get in.",
  "Listen.",
  "Ask questions. Before you try to solve.",
  "Make a shared spreadsheet of every restaurant near your office. Include a notes column.",
  "Remember why you wanted this job in the first place.",
  "Who helped you celebrate your last big win at work?",
  "Who helped you fix it your last big mess at work?",
  "Interns are people, too.",
  "Your best network ten years from now will be your peers today. How are they doing?",
  "Who can help this job become the job you want it to be?",
  "Call them on the phone.",
  "Unmute.",
  "Be the supportive nod during someone's presentation.",
  "Remember. Your colleagues have a whole, entire life outside of work. Just like you.",
  "If you're stuck on a problem, talk it through with a peer.",
  "Host a meeting outside.",
  "Wave to the people who are stuck in the fishbowl meeting room.",
  "Make an email introduction for two excellent humans. Include the excellence in your note.",
  "Make a full pot.",
  "Remember what it was like to be new.",
  "Remember what it was like to be young.",
  "Remember what it was like to be unsure.",
  "Bring others along.",
  "No observers. Only participants.",
  "Put your phone down.",
  "Close your laptop.",
  "Make time for small talk.",
  "If it works on your machine, help someone fix it on theirs.",
  "Run a lunch and learn on something that only the old guard remembers.",
  "Guest lecture for a group of students.",
  "Stop typing in other windows. We can all tell.",
  "Work from the kitchen.",
  "What can you learn from the most junior person on the team?",
  "Who needs help celebrating a win?",
  "Who needs help recovering from a setback?",]
