const PROMPTS = [
  "Listen.",
  "Unmute.",
  "Find the time.",
  "Make the time.",
  "Mentor someone.",
  "Invite dissent.",
  "Make a full pot.",
  "Ask the question.",
  "Close your laptop.",
  "Bring others along.",
  "Put your phone down.",
  "Pick someone's brain.",
  "Work from the kitchen.",
  "Call them on the phone.",
  "Host a meeting outside.",
  "Interns are people, too.",
  "Make time for small talk.",
  "Turn your camera back on.",
  "You were junior once, too.",
  "Let someone pick your brain.",
  "Sign off. Try again tomorrow.",
  "Remember, someone mentored you.",
  "You can't solve this one alone.",
  "Make space for others to get in.",
  "Leave room for others to get in.",
  "No observers. Only participants.",
  "Be the first to put your hand up.",
  "Who needs help celebrating a win?",
  "Your undivided attention is a gift.",
  "Your output is someone else's input.",
  "You're allowed to ask for help, too.",
  "Thank the EA who booked the meeting.",
  "Remember what it was like to be new.",
  "Notice how far you've come together.",
  "Remember what it was like to be young.",
  "Guest lecture for a group of students.",
  "Check in with them instead of guessing.",
  "Who's falling off-grid? Pull them back.",
  "Ask the CEO what they're worried about.",
  "Remember what it was like to be unsure.",
  "It's the friends you make along the way.",
  "Memorize the receptionist's coffee order.",
  "Who needs help recovering from a setback?",
  "Eat at a lunch counter without your phone.",
  "Find out people's birthdays. Do something.",
  "React with words instead of just an emoji.",
  "Ask your boss what they're optimistic about.",
  "Someone new just started. Introduce yourself.",
  "Someone did something great today. Tell them!",
  "Ask colleagues about their favorite projects.",
  "Book a meeting that could have been an email.",
  "Stop typing in other windows. We can all tell.",
  "Stop texting under the table. We can all tell.",
  "Have lunch. Even if you're in different cities.",
  "Ask two more questions before you try to solve.",
  "If you can do it alone, you're thinking too small.",
  "Moving someone to bcc is an opportunity for whimsy.",
  "Meet for coffee. Even if you're in different cities.",
  "Ask the interns how they chose their favorite class.",
  "Remember why you wanted this job in the first place.",
  "Be the supportive nod during someone's presentation.",
  "Remember what it felt like when you got the job offer.",
  "What do you wish knew more about? Who is great at that?",
  "Who can help this job become the job you want it to be?",
  "Identify key stakeholders < Say hello to key stakeholders",
  "Ask an exec which part of the strategy excites them most.",
  "If you're stuck on a problem, talk it through with a peer.",
  "Have a walking meeting. Even if you're in different cities.",
  "If it works on your machine, help someone fix it on theirs.",
  "What can you learn from the most junior person on the team?",
  "Grunt work goes fast when divided across a team with snacks.",
  "Your best network ten years from now will be your peers today.",
  "Wave to the people who are stuck in the fishbowl meeting room.",
  "When was the last time someone took an interest in your career?",
  "Make a friend in an industry you're curious to learn more about.",
  "Who helped you fix it your last big mess at work? Say thank you.",
  "Connecting people is righteous. Remember, double opt-in or bust.",
  "Adding someone to a very long thread is an opportunity for whimsy.",
  "The goal isn't to do everything. Talk about what's most important.",
  "Who helped you celebrate your last big win at work? Say thank you.",
  "Hydration matters. Give people time to get water before the meeting.",
  "Set up a video portal for multi-city offices. Put it in the kitchen.",
  "Invite the entire meeting to unclench their jaws before you kick off.",
  "Run a lunch and learn on something that only the old guard remembers.",
  "Who helped you get your current gig? Have you spoken with them lately?",
  "Invite the entire meeting to drop their shoulders before you kick off.",
  "Someone did something great last week. Tell them why it mattered to you.",
  "Book a meeting with a colleague to just sit together and get your shit done.",
  "Organize happy hour. Remember, not everyone has the same definition of happy.",
  "Zoom is faster. In-person is more meaningful. Pick the right tool for the job.",
  "Your colleague just got back from travel. Ask them about the best thing they ate.",
  "Show your colleagues how something works. You may need to screenshare. That's ok.",
  "Ask a question. Pause and drink water while you wait for the next person to speak.",
  "Remember. Your colleagues have a whole, entire life outside of work. Just like you.",
  "Introductions are an opportunity to say kind, generous things about two cool people.",
  "Say thank you. Can't figure out what for? Close your eyes and count to ten. It'll come.",
  "Make a shared spreadsheet of every restaurant near your office. Include a notes column.",
  "Who — other than a bot — can teach you about the thing you're struggling with right now?",
  "Make an email introduction for two excellent humans. Include the excellence in your note.",
  "Find the most junior person on the team. Teach them something it took you months to learn.",
  "You're not sure how someone feels about your work. Check in with them instead of guessing.",
  "Have your colleague teach you how something works. They may need to screenshare. That's ok.",
  "Together, imagine the best version of that complex working relationship. Together, build it.",
  "Global teams make great pen pals. Send predictions from the future. Or missives from the past.",
  "The cure for imposter syndrome is objectivity. Ask a colleague how they thought that meeting went.",
  "Can your next virtual meeting be over coffee? What if you were willing to restructure or reschedule it?",
]
